version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 377021732766.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t demo .
      - docker tag demo:latest 377021732766.dkr.ecr.us-east-1.amazonaws.com/demo:latest
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 377021732766.dkr.ecr.us-east-1.amazonaws.com/demo:latest
      - printf '[{"name":"demo","imageUri":"377021732766.dkr.ecr.us-east-1.amazonaws.com/demo:latest"}]' > imagedefinition.json
artifacts:
  files:
    - imagedefinition.json
